server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/shophub
    username: shophub
    password: shophub
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka

resilience4j:
  retry:
    instances:
      productClient:
        max-attempts: 3
        wait-duration: 1000ms
